title: Cindy Lim
logo: /assets/img/logo.png
email: cindy.lim@bristol.ac.uk
description: Geophysics PhD student. Alan Turing Enrichment Community Scheme student. Bruneian.
favicon: true
color-scheme: auto
url: "https://cindylim.com/"

# Build settings
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
plugins:
  - jekyll-seo-tag
  - jemoji
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap

platforms:
  - name: Research
    icon: <i class="fa-solid fa-book-bookmark"></i>
    link: https://cindylim.com/research.html
  - name: Mastodon
    icon: <i class="fab fa-mastodon"></i>
    link: https://mastodon.lol/@swarls_lim
  - name: Twitter
    icon: <i class="fa-brands fa-twitter"></i>
    link: https://twitter.com/swarls_lim
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/cl16908

navigation:
  - name: Home Page
    link: ./index.html
    sublist:
      - name: About Me
        link: /#about-me
      - name: Education
        link: /#education
      - name: Skills
        link: /#skills
      - name: Experience
        link: /#experience
      - name: Achievements and Awards
        link: /#achievements-and-awards
  - name: Research
    link: ./research.html

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
